---
- name: Copy master service file
  template:
    src: hbase-master.ini.j2
    dest: "{{ supervisord_ini_dir }}/hbase-master.ini"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: "u=rw,g=r,o=r"
  when: '"master" in group_names'
  notify:
    - Update supervisord
    - Restart hbase-master

- name: Copy regionserver service file
  template:
    src: hbase-regionserver.ini.j2
    dest: "{{ supervisord_ini_dir }}/hbase-regionserver.ini"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: "u=rw,g=r,o=r"
  when: '"data" in group_names'
  notify:
    - Update supervisord
    - Restart hbase-regionserver

- name: put config.yml
  template:
    src: config.yml
    dest: "{{ hbase_conf_dir }}/config.yml"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: no
  register: config_yml
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

- name: put hbase-site.xml
  template:
    src: hbase-site.xml
    dest: "{{ hbase_conf_dir }}/hbase-site.xml"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: no
  register: hbase_site_xml
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

- name: put hbase-policy.xml
  template:
    src: hbase-policy.xml
    dest: "{{ hbase_conf_dir }}/hbase-policy.xml"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: no
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

- name: put hbase-env.sh
  template:
    src: hbase-env.sh
    dest: "{{ hbase_conf_dir }}/hbase-env.sh"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0755
    backup: no
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

- name: put log4j.properties
  template:
    src: log4j.properties
    dest: "{{ hbase_conf_dir }}/log4j.properties"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: no

- name: put hadoop-metrics2-hbase.properties
  template:
    src: hadoop-metrics2-hbase.properties
    dest: "{{ hbase_conf_dir }}/hadoop-metrics2-hbase.properties"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: no

- name: put jmxremote.access
  template:
    src: jmxremote.access
    dest: "{{ hbase_conf_dir }}/jmxremote.access"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: no

- name: put jmxremote.passwd
  template:
    src: jmxremote.passwd
    dest: "{{ hbase_conf_dir }}/jmxremote.passwd"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0600
    backup: no

- name: create hdfs-site.xml
  file:
    state: link
    src: "{{ hdfs_conf_dir }}/hdfs-site.xml"
    dest: "{{ hbase_conf_dir }}/hdfs-site.xml"

- name: create core-site.xml
  file:
    state: link
    src: "{{ hdfs_conf_dir }}/core-site.xml"
    dest: "{{ hbase_conf_dir }}/core-site.xml"
