---
- name: put hbase-site.xml
  template:
    src: hbase-site.xml
    dest: "{{ hbase_conf_dir }}/hbase-site.xml"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: yes
  register: hbase_site_xml
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

- name: put hbase-policy.xml
  template:
    src: hbase-policy.xml
    dest: "{{ hbase_conf_dir }}/hbase-policy.xml"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0644
    backup: yes
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

- name: put hbase-env.sh
  template:
    src: hbase-env.sh
    dest: "{{ hbase_conf_dir }}/hbase-env.sh"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: 0755
    backup: yes
  notify:
    - Restart hbase-master
    - Restart hbase-regionserver

  #- name: put "/etc/hbase/conf/log4j.properties"
  #template: src=log4j.properties dest=/etc/hbase/conf/log4j.properties owner=root group=root mode=0644 backup=yes

  #- name: put "/etc/hbase/conf/hadoop-metrics2-hbase.properties"
  #template: src=hadoop-metrics2-hbase.properties dest=/etc/hbase/conf/hadoop-metrics2-hbase.properties owner=root group=root mode=0644 backup=yes

- name: create hdfs-site.xml
  file:
    state: link
    src: "{{ hdfs_conf_dir }}/hdfs-site.xml"
    dest: "{{ hbase_conf_dir }}/hdfs-site.xml"

- name: create core-site.xml
  file:
    state: link
    src: "{{ hdfs_conf_dir }}/core-site.xml"
    dest: "{{ hbase_conf_dir }}/core-site.xml"
