---
- name: "Create hbase Path {{ hbase_install_dir }}"
  file:
    path: "{{ hbase_install_dir }}"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: create dir {{ hbase_install_dir }}/{{ hbase_version }}
  file:
    path: "{{ hbase_install_dir }}/{{ hbase_version }}"
    state: directory
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    mode: "u=rwx,g=rwx,o=rwx"

- name: "Create hbase log Path {{ hbase_log_dir }}"
  file:
    path: "{{ hbase_log_dir }}"
    owner: "{{ hbase_user }}"
    group: "{{ hbase_group }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- import_tasks: install.yml
  tags: install

- import_tasks: config.yml
  tags: config
